### ISSUE TITLE
Python version 

### ISSUE THREAD

**Issue by marcinlaskowski-sempai** [google-marketing-solutions/ga4_dataform#4]
I tried couple times to configure Dataform using the repository with dataset that is located in multiregion UE. 
I pointed during one of configuration steps 

```
./deploy.sh [Project-name]\
europe-west6 \
UE
```

And I received error message 'no dataset in location'

I created dataset replica in 'europe-central2'
And then proceeded with configuration again and after 

command: 
```
$ ./deploy.sh dataform-test-07 \
europe-west6 \
europe-central2
```

I received an error :

Updated property [core/project].
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement cachetools==5.3.1 (from -r requirements.txt (line 7)) (from versions: 0.0.0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 2.0.0, 2.0.1, 2.1.0, 3.0.0, 3.1.0, 3.1.1)
ERROR: No matching distribution found for cachetools==5.3.1 (from -r requirements.txt (line 7))
Traceback (most recent call last):
  File "/home/marcin_laskowski/ga4_dataform/main.py", line 17, in <module>
    from google.cloud import dataform_v1beta1
ImportError: cannot import name 'dataform_v1beta1' from 'google.cloud' (unknown location)
ERROR: (gcloud.projects.add-iam-policy-binding) INVALID_ARGUMENT: Service account [service-222744716423@gcp-sa-dataform.iam.gserviceaccount.com](mailto:service-222744716423@gcp-sa-dataform.iam.gserviceaccount.com) does not exist.
ERROR: (gcloud.projects.add-iam-policy-binding) INVALID_ARGUMENT: Service account [service-222744716423@gcp-sa-dataform.iam.gserviceaccount.com](mailto:service-222744716423@gcp-sa-dataform.iam.gserviceaccount.com) does not exist.

I wonder if python error could be repaired on my side? 
And what are the proper settings in step:
```
$ ./deploy.sh dataform-test-07 \
Dataform Location \
Dataset Location
```

Considering the fact that the original dataset is in 'UE' multiregion (and replica in 'europe-central2' region ) and Dataform is not available in 'europe-central2' region according to this list:
https://cloud.google.com/dataform/docs/locations
Kind regards, Marcin

**Comment by piariachi** [comment]
Hello @marcinlaskowski-sempai the list of supported BQ locations could be referenced here: https://cloud.google.com/bigquery/docs/locations (UE is not part of the list). Also make sure the region matches the region of your GA4 events_table.

Also note that we have updated the repo to use a different deployment method which is by connecting to a GitHub repo, this is the recommended approach by Dataform.

If you still want to use the deploy.sh file, you could edit the code inside main.py to use pip3 instead of pip, and python3 instead of python (it seems your default python version is still 2, and hence the error)
