### ISSUE TITLE
bing/cpc missing from session tables

### ISSUE THREAD

**Issue by gldsv** [google-marketing-solutions/ga4_dataform#5]
Hi, when comparing a simple source acquisition report using this query below and comparing to a GA4 UI Explore on the same perimeter, I notice the source/medium bing/cpc is missing from the ga4_dataform_output data. 

```
SELECT
  last_non_direct_traffic_source.source,
  last_non_direct_traffic_source.medium,
  COUNT(*) AS nb_sessions
FROM `useful-foundry-132723.ga4_dataform_output.session` 
WHERE session_start_date BETWEEN "2024-04-01" AND "2024-04-30"
GROUP BY 1,2
ORDER BY 3 DESC
```

The query outputs this:
![image](https://github.com/google-marketing-solutions/ga4_dataform/assets/108370876/757660a1-0142-4325-9197-0ba5edfff6c2)

The GA4 UI Explore reports this:
![image](https://github.com/google-marketing-solutions/ga4_dataform/assets/108370876/c895f1e3-80e1-46db-9fe6-402d6f652808)

**Comment by piariachi** [comment]
Hi @gldsv thanks for raising this, from your data, it seems that bing/cpc might have been allocated to Google/cpc. 
Note: While it might be on the roadmap for GA4 BQ exports, cpc traffic sources are still not tracked by default in the exports, so this solution attempts a workaround function to overcome this (you can find it in helpers.js >updatePaidSearchTrafficSource)
Question: could you check if the rows that should be corresponding to bing/cpc have values in the 'collected_traffic_source.gclid' column?

**Comment by piariachi** [comment]
Makes absolute sense Matt! I can confirm that this happens when using SA360
to manage bing. Thanks for sharing the logic here.
