### ISSUE TITLE
"Run with Full Refresh" fails with timeout

### ISSUE THREAD

**Issue by edkaizen** [google-marketing-solutions/ga4_dataform#7]
hi,

We installed the dataform scripts as instructed, and we executed the Full Refresh for one day (start day 30th June), then for one week (start date 24th June), and both finished successfully.

When we are defining an earlier start date like 01-Jan-2024 or 01-Mar-2024 (by updating constants.js file), one of the processes ends in error with timeout, as you can see in the screenshots.

![Screenshot 2024-07-03 at 17 08 06](https://github.com/google-marketing-solutions/ga4_dataform/assets/174343844/f66dd2ee-cad2-4b14-ad6b-af66913902db)
![Screenshot 2024-07-03 at 17 09 12](https://github.com/google-marketing-solutions/ga4_dataform/assets/174343844/a19034bb-92f7-41da-ad74-05d707595d4c)
![Screenshot 2024-07-03 at 17 12 55](https://github.com/google-marketing-solutions/ga4_dataform/assets/174343844/f27837eb-5a6a-41c5-8318-69f3d0d3df4c)

From our initial investigations we found out that all the data seems to be present in the sessions output table but not the events output table.

Can you please provide information about how to diagnose this issue, or maybe provide instructions about how to submit the executions with smaller batches of data/dates. Is it even possible to submit smaller date ranges due to the lookback windows?

**Comment by piariachi** [comment]
Hey @edkaizen , could you confirm you are using the latest commit of the GitHub repository? (There has been some optimizations done to the event query)

Also note, the event attribution model does not affect session attribution, so in case you are only interested in session attribution , you are good to ignore the events model.

You could also try loading it in smaller batches, but please make sure the date range goes back to the lookback window at a minimum.

**Comment by edkaizen** [comment]
hi @piariachi thank you for the feedback. We pulled the repo around 30th June, and I can see that the last commit is 28th May, so I am safely assuming that we are using the latest commit.

In the meantime I have some more screenshots of the query and error that is causing the failure I will upload them here. It is a join that is being done at the last steps of the sessions process. Do you suggest any solution for this?

![execution_graph](https://github.com/google-marketing-solutions/ga4_dataform/assets/174343844/18abb8a5-17b4-4d64-9702-6e01edcf923b)
![execution_graph_s01_input](https://github.com/google-marketing-solutions/ga4_dataform/assets/174343844/13dde56b-1ca9-42fa-8d28-c24f31c1b2a5)
![execution_graph_S01_Join_1](https://github.com/google-marketing-solutions/ga4_dataform/assets/174343844/9aa44bf8-736b-4da4-ae09-52fa2678f61c)
![execution_graph_S01_Join_2](https://github.com/google-marketing-solutions/ga4_dataform/assets/174343844/3273f321-06a5-449d-b30a-2b25ad822980)
![execution_graph_S01_Join_3](https://github.com/google-marketing-solutions/ga4_dataform/assets/174343844/5be858e4-04d8-4df4-b1e3-71520f06e258)

Regarding loading in smaller batches, can you please provide instructions of how to do that? Do we need to move the Start Date month by month backwards (from the constants.js file) and the run ALL ACTIONS and DO NOT select "Run with Full Refresh"? How will the lookback window queries work in that case?

**Comment by piariachi** [comment]
Thanks for sharing the screenshots, the is definitely related to large data volume. I do not have an alternative query at the moment unfortunately.

Would excluding un-necessary events from the staging layer help here? I have seen that a lot of datasets have 70%+ events that are just informational and custom (as opposed to the core events page_view, session_start, purchase etc...)

For smaller batches, the models do not support this and you would need to manually configure that for now. The current code only supports a recent 'start_date' but not 'end_date'...

**Comment by edkaizen** [comment]
hi @piariachi , we have followed your suggestion to optimise the queries in the output events file event.sqlx since the dataform was getting stuck for hours in this step. Specifically it was getting stuck in the "final as (" part since there is a sub-query within the select statement for all the events, which is very inefficient. The subquery was to sort out the last click attribution with the two lookback windows:

`final as (
    select
    a.*,
    if(coalesce(nullif(a.collected_traffic_source.source, '(direct)'), nullif(a.collected_traffic_source.medium, '(none)'), nullif(a.collected_traffic_source.campaign, '(direct)')) is null,
    (
    select
    array_agg(b.collected_traffic_source)
    from
    int_event as b
    where
    b.user_key = a.user_key
    and cast(b.event_timestamp / 1000000 as int64) >= (cast(a.event_timestamp / 1000000 as int64) -
    case
    when a.event_name in ('first_visit', 'first_open') then ${constants.AQUISITION_EVENTS_LOOKBACK_WINDOW}
    else
    ${constants.ALL_EVENTS_LOOKBACK_WINDOW}
    end
    )
    and cast(b.event_timestamp / 1000000 as int64) <= cast(a.event_timestamp / 1000000 as int64)
    and coalesce(nullif(b.collected_traffic_source.source, '(direct)'), nullif(b.collected_traffic_source.medium, '(none)'), nullif(b.collected_traffic_source.campaign, '(direct)')) is not null)[safe_offset(0)],
    a.collected_traffic_source
    ) as last_non_direct_traffic_source
    from
    int_event as a )`

I had a look at the sessions.sqlx file since this also queries the events table but finishes in minutes, the main difference though is that it only has the sessions lookback window and not the acquisition one too. So I have attempted to get the main query structures from the sessions.sqlx file and adapt them to the events file. It seems to be successful i terms of optimisation since the script now ends in like 30 mins rather than timing out after 9 hours. However I would need some help to verify the script and some direction of how to QA the resulting output data. I will upload the events file for your review.

[event.sqlx.zip](https://github.com/user-attachments/files/16359765/event.sqlx.zip)

**Comment by piariachi** [comment]
Hi @edkaizen thanks for sharing the optimized query. I tried it on a dataset and the logic looks fine. I haven't gotten the chance to QA the results yet, but will add it to my todo.
