### ISSUE TITLE
Mulitple Google Ads Customer IDs

### ISSUE THREAD

**Issue by edkaizen** [google-marketing-solutions/ga4_dataform#9]
hi @piariachi we have noticed that ga4_dataform constants.js file only takes one set of GADS_CUSTOMER_ID setup, however our GA4 property is linked to multiple Google Ads accounts. This means that our bigquery dataset for our property has data from these multiple google ads accounts. What is the recommended or supported way to go about this scenario please?

Thank you!

**Comment by piariachi** [comment]
Hi @edkaizen the tool currently doesn't support multiple Google Ads Accounts. One way to do this is to create one view with all google ads properties before using in Dataform. 
Also take note of the latest announcement that session source traffic information is now native to the GA4 BQ exports, so a lot of the current logic is not needed anymore: https://support.google.com/analytics/answer/9164320?hl=en#071924

**Comment by edkaizen** [comment]
hi @piariachi , many thanks for the quick reply and for the hint regarding the possible fix with the view.

If I understood correctly this [fixes/updates](https://support.google.com/analytics/answer/9164320?hl=en#071924) from google will make the following points from ga4_dataform deprecated right:

_- Determining the channels that initiated the session (based on last click) and attributing those channels to the first session traffic sources.
- Providing an example of how a custom session attribution logic could be implemented by computing the last non-direct traffic source for the session.
- Gclid widening by mapping the GA4 gclid to the Google Ads Data Transfer click-view gclid (Optional setting)
Event level last-click attribution._

I am aware that the current version of GA4 dataform is suitable to fix historical bigquery data, but is there a plan to update/maintain this GA4_dataform Repository to cater for the updates in the BigQuery schema that were released in July? I am asking since this will also impact positively the performance issues I have reported in [issue 7](https://github.com/google-marketing-solutions/ga4_dataform/issues/7).

**Comment by piariachi** [comment]
Hi @edkaizen , yes correct, the points you mentioned will get deprecated.
There are plans to update the code, but no ETA yet. The new codebase will not cater for both historical and new schemas, it would only be updated to reflect the new schemas. So most likely, you would need to generate your historical data once using the old code, and use the new code for data coming in July onwards.
Hope this makes sense.

**Comment by edkaizen** [comment]
hi @piariachi , thank you for the clarifications. You can close this ticket.

In terms of running the current/old code for our ecosystem, as I described in [issue 7](https://github.com/google-marketing-solutions/ga4_dataform/issues/7) we are facing script performance issues, but I think I found a way around it and I will post it in that ticket.

**Comment by piariachi** [comment]
Perfect! Glad to hear you found a way :)
